---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sample-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/WASdev/ci.docker.websphere-traditional
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sample-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/hello-world-pipeline/sample:latest
